package json.service;

public enum EJsonOperationStatus {
    INVALID_ARGUMENT, SUCCESS, SUCCESS_NO_CHANGES, UNKNOWN_ERROR, INVALID_CONFIGURATION, DICTIONARY_CREATION_PROBLEM,
    REST_CLIENT_ERROR, IO_ERROR
}
